### ISSUE TITLE
TODO tracker

### ISSUE THREAD

**Issue by fsantini** [dafne-imaging/dafne#1]
This issue tracks all the enhancements that are required for Dafne.

### Core functionality
- [ ] Deep Learning integration
  - [x] Definition of Interface classes for DL tasks - needs to be general enough to allow for inherent splitting of images etc
  - [x] Image standardization (resampling/FOV?)
    - [ ] More general standardization (orientation check...)
  - [x] Server integration
  - [x] Incremental learning
  - [x] Retraining of the model on a single side
- [x] Calculation of quality metrics (dice score before and after refinement)
### Interface
- [ ] Patient/data browser
- [ ] PACS search
- [x] Interface tweak for separate toolbox
- [x] Import/Export of ROIS
- [ ] Export of Masks
  - [x] Numpy
  - [x] DICOM
  - [x] Nifti
- [x] Import of Masks
- [x] Show segmentation statistics
- [x] Translate contour
- [x] Rotate contour
### Wishlist
- [ ] Model encryption
