### ISSUE TITLE
Road to first milestone

### ISSUE THREAD

**Issue by fsantini** [dafne-imaging/dafne#2]
This issue tracks the exact todo for the first milestone release.
### dafne.py

- [x] Insert RemoteModelProvider as replacement for LocalModelProvider (add command line option for choice)

### ui/MuscleSegmentation.py
- [x] In saveResults() add:
   - [x] Calculation of delta model?
   - [ ] Model/Delta model upload to server
      - [ ] Consider a different approach for delta calculation that sets to zero the weights below a threshold - then we can probably use standard zlib to reduce the upload size
   - [ ] Dice score upload to server (dice scores are already calculated)

### Server
- [ ] Deployment of the server (@wasserth )
   - [ ] As Docker?
